export const jobExperience = [
  {
    id: 1,
    name: "TheMatrix",
    duration: "Dec 2022 - Present",
    role: "Full-Stack Developer Intern",
    desc: [
      "Developed UI components with Next.js and Typescript to allow users to import and export contacts",
      "Designed API endpoints and incorporated file handling with file interceptors and custom pipes in Nest.js",
      "Implemented CRUD operations with Prisma ORM and PostgreSQL for efficient data management",
      "Built a service that interacts with Google Cloud Tasks for sending emails",
      "Crafted a cronjob-powered script to automate the clearing of cache for yarn and npm on a regular basis",
      "Configured Gitlab CI/CD pipeline with Google Cloud SQL and Cloud Run to connect the project to Cloud PSQL",
      "Created comprehensive unit tests with 90% coverage with Jest testing framework",
    ],
    skills: ["React", "SCSS", "TypeScript", "Prisma", "SQL", "Next"],
  },
  {
    id: 2,
    duration: "Mar 2021-Present",
    name: "The Logic Coders",
    role: "Tutor",
    desc: [
      "Taught python programming to more than 30 students aged 8 and above, covering from syntax to libraries",
      "Guided more than 30 students aged 6 and above on using drag and drop programming and EV3 Lego sets",
      "Coordinated trial classes resulting in 5 new students",
      "Enriched young children to develop logical thinking skills and refine cognitive abilities",
      "Conducted meetings with students’ parents to gather feedbacks and discuss ways to improve students’ learning",
      " Trusted to design personal curriculum for 5 students, receiving positive feedbacks from students and parents",
    ],
  },
  {
    id: 3,
    name: "Elitely",
    duration: "Mar 2022 - Aug 2022",
    role: "Full-Stack Developer",
    desc: [
      "Collaborated with 3 developers to develop a website including user authentication and payment integration",
      "Designed schemas and built a database in MongoDB to store personal details of users",
      "Executed and managed user authentication and file storage system with AWS Amplify and AWS S3",
      "Integrated payment features using APIs, Stripe and NodeJS",
      "Supervised a team of 2 regarding application’s database and backend",
    ],
    skills: ["React", "TypeScript", "SQL", "Next"],
  },
];
